name: sync upstream

on:
  workflow_dispatch:
  schedule:
    # Run every day one hour to midnight
    - cron: '0 23 * * *'

jobs:
  sync_upstream:
    name: Sync upstream
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout main
        uses: actions/checkout@v6
        with:
          path: main
          ref: main
      - name: Checkout mainCI
        uses: actions/checkout@v6
        with:
          path: mainCI
          ref: mainCI
      - name: Sync upstream
        working-directory: ./main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "username@users.noreply.github.com"
          git remote add upstream https://github.com/microsoft/playwright.git
          git pull upstream main
          git push
          git branch -f mainCI main
          git checkout mainCI
          rm .github/workflows/*
          cp ../mainCI/.github/workflows/* .github/workflows/
          git add .
          git commit -m "CI changes"
          git push -f origin mainCI
